all:
	@$(MAKE) -C fractals
	@$(MAKE) -C games
	@$(MAKE) -C hires
	@$(MAKE) -C hiresmc
	@$(MAKE) -C particles
	@$(MAKE) -C kernalio
	@$(MAKE) -C memmap
	@$(MAKE) -C rasterirq
	@$(MAKE) -C scrolling
	@$(MAKE) -C sprites
	@$(MAKE) -C stdio

clean:
	@$(MAKE) -C fractals $@
	@$(MAKE) -C games $@
	@$(MAKE) -C hires $@
	@$(MAKE) -C hiresmc $@
	@$(MAKE) -C particles $@
	@$(MAKE) -C kernalio $@
	@$(MAKE) -C memmap $@
	@$(MAKE) -C rasterirq $@
	@$(MAKE) -C scrolling $@
	@$(MAKE) -C sprites $@
	@$(MAKE) -C stdio $@
